spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format-sql: true
        use-sql-comments: true

  datasource:
    url: jdbc:h2:mem:order
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  servlet:
    session:
      timeout: 30m
      tracking-modes: cookie




logging:
  config: classpath:logback-local.xml

